import { randomUUID } from "node:crypto";
import { appendFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import {
	PLANNOTATOR_NOT_READY_ERROR,
	markHandled,
	wasEverHandled,
} from "./plannotator-readiness.js";

const DEBUG_LOG_PATH = join(homedir(), ".pi", "tff-plannotator-debug.log");
let debugDirEnsured = false;

function debugLog(event: string, fields: Record<string, unknown>): void {
	try {
		if (!debugDirEnsured) {
			mkdirSync(dirname(DEBUG_LOG_PATH), { recursive: true });
			debugDirEnsured = true;
		}
		const line = JSON.stringify({ ts: new Date().toISOString(), event, ...fields });
		appendFileSync(DEBUG_LOG_PATH, `${line}\n`);
	} catch {
		// Diagnostic logging must never break the review flow.
	}
}

export interface ReviewResult {
	approved: boolean;
	feedback?: string;
}

interface PlannotatorHandledResponse {
	status: "handled";
	result: { status: "pending"; reviewId: string };
}
interface PlannotatorUnavailableResponse {
	status: "unavailable";
	error?: string;
}
interface PlannotatorErrorResponse {
	status: "error";
	error?: string;
}
type PlannotatorResponse =
	| PlannotatorHandledResponse
	| PlannotatorUnavailableResponse
	| PlannotatorErrorResponse;

interface PlannotatorReviewResultEvent {
	reviewId: string;
	approved: boolean;
	feedback?: string;
}

export interface ReviewRequest {
	requestId: string;
	action: "plan-review";
	payload: {
		planContent: string;
		planFilePath?: string;
	};
	respond: (response: PlannotatorResponse) => void;
}

export function buildReviewRequest(
	requestId: string,
	artifactPath: string,
	content: string,
	_reviewType: "spec" | "plan",
): Omit<ReviewRequest, "respond"> {
	return {
		requestId,
		action: "plan-review",
		payload: {
			planContent: content,
			planFilePath: artifactPath,
		},
	};
}

const REVIEW_RESULT_CHANNEL = "plannotator:review-result";
const REVIEW_REQUEST_CHANNEL = "plannotator:request";

/**
 * Waits up to 5 minutes for the user to approve/reject in plannotator.
 *
 * Handshake contract (see @plannotator/pi-extension plannotator-events.ts):
 *
 * 1. We emit on `plannotator:request` with our `requestId` + a `respond`
 *    callback.
 * 2. Plannotator responds synchronously via `respond({status:"handled",
 *    result:{status:"pending", reviewId}})` where `reviewId` is a NEW id
 *    generated by plannotator — NOT our requestId. (Prior versions of this
 *    file wrongly matched events against our requestId, so every approval
 *    event failed to match, the timeout always fired, and every review
 *    silently auto-approved.)
 * 3. When the user clicks approve/deny in the browser, plannotator emits
 *    on `plannotator:review-result` with that plannotator-assigned
 *    `reviewId`. We match against the stored id and resolve.
 *
 * If plannotator responds `unavailable`/`error`, we auto-approve immediately
 * so the workflow isn't blocked in setups without plannotator. If the
 * response never arrives, we auto-approve after the timeout.
 */
export const DEFAULT_REVIEW_TIMEOUT_MS = 10 * 60_000;

export function requestReview(
	pi: ExtensionAPI,
	artifactPath: string,
	content: string,
	reviewType: "spec" | "plan",
	opts: { timeoutMs?: number } = {},
): Promise<ReviewResult> {
	return new Promise((resolve) => {
		const requestId = randomUUID();
		const timeoutMs = opts.timeoutMs ?? DEFAULT_REVIEW_TIMEOUT_MS;
		let resolved = false;
		// Plannotator mints its OWN reviewId and uses that in the result event,
		// ignoring our requestId. We must capture the plannotator-assigned id
		// from the `handled` response and match against it.
		let plannotatorReviewId: string | null = null;

		debugLog("request_start", { requestId, artifactPath, reviewType, timeoutMs });

		const finish = (result: ReviewResult) => {
			if (resolved) return;
			resolved = true;
			unsubscribe();
			clearTimeout(timer);
			debugLog("finish", { requestId, plannotatorReviewId, result });
			resolve(result);
		};

		const timer = setTimeout(() => {
			debugLog("timeout", { requestId, plannotatorReviewId, timeoutMs });
			finish({ approved: true, feedback: "Review timed out — auto-approved" });
		}, timeoutMs);

		const unsubscribe = pi.events.on(REVIEW_RESULT_CHANNEL, (data: unknown) => {
			const event = data as Partial<PlannotatorReviewResultEvent> | null | undefined;
			if (!event || typeof event.reviewId !== "string") {
				debugLog("result_ignored_malformed", { requestId, data });
				return;
			}
			// Match against the plannotator-assigned id (learned via `handled` response).
			// Fall back to our requestId for back-compat with consumers that honor it.
			const matchPlannotator = !!(plannotatorReviewId && event.reviewId === plannotatorReviewId);
			const matchRequest = event.reviewId === requestId;
			const match = matchPlannotator || matchRequest;
			debugLog("result_received", {
				requestId,
				plannotatorReviewId,
				eventReviewId: event.reviewId,
				approved: event.approved,
				matchPlannotator,
				matchRequest,
				match,
			});
			if (!match) return;

			const result: ReviewResult = { approved: event.approved === true };
			if (event.feedback !== undefined) result.feedback = event.feedback;
			finish(result);
		});

		const request = buildReviewRequest(requestId, artifactPath, content, reviewType);
		debugLog("emit_request", { requestId, channel: REVIEW_REQUEST_CHANNEL });
		pi.events.emit(REVIEW_REQUEST_CHANNEL, {
			...request,
			respond: (response: PlannotatorResponse) => {
				debugLog("respond_received", {
					requestId,
					status: response.status,
					reviewId: response.status === "handled" ? response.result?.reviewId : undefined,
					error:
						response.status === "unavailable" || response.status === "error"
							? response.error
							: undefined,
				});
				if (response.status === "handled") {
					markHandled();
					if (response.result?.reviewId) {
						plannotatorReviewId = response.result.reviewId;
					}
					return;
				}
				if (response.status === "unavailable" || response.status === "error") {
					const isContextNotReady = response.error === PLANNOTATOR_NOT_READY_ERROR;
					const plannotatorActive = wasEverHandled() || isContextNotReady;
					debugLog("respond_unavailable_decision", {
						requestId,
						isContextNotReady,
						wasEverHandled: wasEverHandled(),
						plannotatorActive,
						action: plannotatorActive ? "keep_listening" : "auto_approve",
					});
					if (plannotatorActive) {
						// Plannotator is mounted (or about to be) — this is a race.
						// Keep our listener alive; the user's eventual approval click
						// will fire plannotator:review-result and we'll pick it up.
						return;
					}
					finish({ approved: true, feedback: "Plannotator unavailable — auto-approved" });
					return;
				}
			},
		});
	});
}
